### ISSUE TITLE
In docker container

### ISSUE THREAD

**Issue by kamenomagic** [vitalidze/chromecast-java-api-v2#100]
I have shared the host network and full privileges to the docker container and still the chromecast api can't find any chromecasts (it works outside of the container). 

I know this is a docker question moreso, but my question for you is:

How does the chromecast discovery API search and find chromecasts?
Do you know of something that the chromecast API does that wouldn't work in a docker container even though the network is shared with the host (same network) and the container has root privileges?

**Comment by vitalidze** [comment]
> How does the chromecast discovery API search and find chromecasts?

It is using [Multicast DNS](https://en.wikipedia.org/wiki/Multicast_DNS) for discovery. I suppose it is sending some request to the networks' multicast address and then waits for response. Maybe you have to configure Docker's networking settings to let the multicast packets pass through to the outer network.

**Comment by kamenomagic** [comment]
https://stackoverflow.com/questions/37214608/docker-receiving-multicast-traffic

That sounds like the solution. Thanks for the insight. 

I will test and report back; if you can leave this open I will make sure to post the solution, could be helpful to users of the repo.

Thanks again.

**Comment by kamenomagic** [comment]
It seems like this may be quite hard (impossible?) to do in a docker container. Can I connect directly to a chromecast via local ip? That might work much easier

**Comment by kamenomagic** [comment]
ChromeCast chromecast = new ChromeCast("192.168.10.36");

Found this, trying

**Comment by kamenomagic** [comment]
Yeah, so for reference, just use the ip when trying to use ChromeCast in a docker container. Discovery is much more difficult to get working due to multicast having issues in the container.

So:
`ChromeCast chromecast = new ChromeCast("192.168.10.36");`

Thanks for the help!

**Comment by vitalidze** [comment]
Thank you very much for an update.
