### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by drak01** [vitalidze/chromecast-java-api-v2#102]
I'm not too familiar with the cast sdk.  So far I just registered a new application, but it's unpublished.  I'm just trying to setup basic usage.

            ChromeCast chromecast = new ChromeCast("192.168.1.2");
		
		//ChromeCast chromecast = ChromeCasts.get().get(0);
		
		try {
			Status status = chromecast.getStatus();
			
			if (chromecast.isAppAvailable("C1BF9585") && !status.isAppRunning("C1BF9585")) {
				  Application app = chromecast.launchApp("C1BF9585");
				}
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		try {
			chromecast.load("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4");
			chromecast.play();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

I get the error,

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
su.litvak.chromecast.api.v2.ChromeCastException: ChromeCast has invalid state to resume media playback
	at su.litvak.chromecast.api.v2.ChromeCast.play(ChromeCast.java:313)
	at application.Main.main(Main.java:40)

(line 40 is chromecast.play())

**Comment by vitalidze** [comment]
This means that at the moment of calling `play()` there is nothing to be played, or there is no media loaded. The status of loaded media can be retrieved with the `getMediaStatus()` method.

FYI, you don't need to call `play()` after calling `load()`. The media playback should be started automatically right after the media is loaded.

**Comment by vitalidze** [comment]
Closed due to inactivity.
