### ISSUE TITLE
few functions not working

### ISSUE THREAD

**Issue by RamiKhawaly** [vitalidze/chromecast-java-api-v2#105]
I'm trying to run the code example suggested on your main page, but few functions are not working 
for example the load function, getStatus or getMedia. all of them get timeout exception. 

can you please advise what is wrong? 

Thanks for the cool library

**Comment by vitalidze** [comment]
This sounds like a network problem. Are you sure your ChromeCast device is accessible from the machine, where you run your code?

I have just checked library with my ChromeCast device and it works just fine.
