### ISSUE TITLE
AuthResponse is incomplete

### ISSUE THREAD

**Issue by Quaffel** [vitalidze/chromecast-java-api-v2#110]
Right now, the AuthResponse message ignores two fields with field index 6 and 7. For more information about the speicified fields, see [here](https://github.com/thibauts/node-castv2/issues/55).

Although the library still works fine without respecting the missing message fields, we should consider implementing them since ignoring fields is never a very satisfying solution. The fields that AuthResponse holds right now are also serving no purpose; so there's no rational reason not to implement them.

**Comment by vitalidze** [comment]
FYI, the recent proto-file specification resides in chromium repository: https://github.com/chromium/chromium/blob/master/components/cast_channel/proto/cast_channel.proto

```proto
message AuthResponse {
  required bytes signature = 1;
  required bytes client_auth_certificate = 2;
  repeated bytes intermediate_certificate = 3;
  optional SignatureAlgorithm signature_algorithm = 4
      [default = RSASSA_PKCS1v15];
  optional bytes sender_nonce = 5;
  optional HashAlgorithm hash_algorithm = 6 [default = SHA1];
  optional bytes crl = 7;
}
```

All fields starting from 4 are marked as optional. It does not make any sense for me to implement them if they are not going to be used.

**Comment by Quaffel** [comment]
Oh, I didn't know that. Thanks!

Maybe you should update the project's README.MD: Right now, the link "Protocol description" leads to the incomplete description I've mentioned. Quite misleading, in my humble opinion. To avoid missunderstandings of this kind in the future, you should consider adding a reference to the .proto-file you've been referering to.

**Comment by vitalidze** [comment]
Done, thank you for your feedback.
