### ISSUE TITLE
 su.litvak.chromecast.api.v2.ChromeCastException: Waiting for response timed out

### ISSUE THREAD

**Issue by HumanG33k** [vitalidze/chromecast-java-api-v2#111]
Hello, i try send url to the chromecast.

I know the Chromecast ip address.
Because i don't want my UI freeze i have done an task class.
This is the code 
```java
          ChromeCast chromecast = new ChromeCast(ip);
            Status status = null;
            try {
                status = chromecast.getStatus();
                 
            } catch (IOException ex) {
                Logger.getLogger(CoreAction.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(chromecast.getName());
            System.out.println(status.toString());
            try {
                chromecast.load(qrCodeUrl);
                chromecast.disconnect();
            } catch (IOException ex) {
                Logger.getLogger(CoreAction.class.getName()).log(Level.SEVERE, null, ex);
            }

```
I guess i have done something wrong because an exeption is trigger.

```
date program.TaskQrCode sendQrCodeToCCast
GRAVE: null
su.litvak.chromecast.api.v2.ChromeCastException: Waiting for response timed out
	at su.litvak.chromecast.api.v2.Channel.send(Channel.java:393)
	at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:348)
	at su.litvak.chromecast.api.v2.Channel.load(Channel.java:495)
	at su.litvak.chromecast.api.v2.ChromeCast.load(ChromeCast.java:457)
	at su.litvak.chromecast.api.v2.ChromeCast.load(ChromeCast.java:433)
	at program.TaskQrCode.sendQrCodeToCCast(TaskQrCode.java:63)
```

**Comment by vitalidze** [comment]
You need to run the application before loading something. Please refer to the instruction in `README.md` of this project.

**Comment by HumanG33k** [comment]
For "standard" usage (send a pic url) i need an app id too ?

**Comment by vitalidze** [comment]
Yes, you need to always use an app.

**Comment by HumanG33k** [comment]
How it's works ?
A chromecast have severals app, each same app have the same id or a same app on several chromecast have the same id. If you know ofc.

**Comment by vitalidze** [comment]
AFAIK you can create your own app for free and then run it on several chromecast devices. It's better to read the official ChromeCast documentation from Google. 

> i already add the code for start & stop the app E8C28D3C from the readme.md.

Not sure where you got this id. It is not present in this project's README.

BTW, I have just tested the library with my simple media receiver app and video from README. It works just fine.

**Comment by HumanG33k** [comment]
i just try to send an url like https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg in order the chromecast.

**Comment by HumanG33k** [comment]
I close for now, i use an other solutions. 

But i guess instead of app i should use send with a custom class and  something like "uri:"/"url:"

thx
