### ISSUE TITLE
Problem from the V0.11.1 of chromecast-java-api-v2

### ISSUE THREAD

**Issue by Fiftiz** [vitalidze/chromecast-java-api-v2#117]
Hello, the day of the V0.11.1 release, there was a problem on openhab with su.litvak.chromecast, MULTIZONE_STATUS problem.

> 2019-09-03 13:22:02.192 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
> 
> org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'MULTIZONE_STATUS' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
> 
>  at [Source: N/A; line: -1, column: -1]
> 
> 	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:452) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:51) ~[206:org.openhab.binding.chromecast:2.4.0]
> 
> 	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:195) [206:org.openhab.binding.chromecast:2.4.0]

Thank you for your help :)

**Comment by Fiftiz** [comment]
@vitalidze

**Comment by vitalidze** [comment]
I believe it has nothing to do with the new version. This is just a type of message ('multi zone status') that is not supported by the library, but is being sent by the chromecast device. To support this type of message I will need an example of the message contents. The example is usually available in the `DEBUG` level of logging.

**Comment by sjonez** [comment]
I think this is what you need @vitalidze 

`2019-09-10 23:32:06.438 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"requestId":0,"status":{"devices":[{"capabilities":196612,"deviceId":"84983351-37c9-1326-3fdd-37ca8b7ff52e","name":"Living Room speaker","volume":{"level":0.30000001192092896,"muted":false}}],"isMultichannel":false},"type":"MULTIZONE_STATUS"}`

`2019-09-10 23:32:06.438 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'MULTIZONE_STATUS' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]`

**Comment by Fiftiz** [comment]
Thank you @sjonez , I didn't have time to make DEBUG :)

**Comment by fkemps** [comment]
Hello Vitalidze,

Do you have enough info to deal with this MULTIZONE_STATUS message?
Let me know if you need more to fix.

Can you give an indication for fix release?

Kind regards,

**Comment by vitalidze** [comment]
I have just pushed a fix. It will be released in nearest minor version of the library. Thank you very much for reporting and for your patience.

**Comment by nav208** [comment]
I need .jar file for openhab. Thanks

**Comment by vitalidze** [comment]
@nav208 well, you can either build it yourself or wait until the next library release.

**Comment by cls2020** [comment]
Tried to build it myself without success:

https://community.openhab.org/t/error-multizone-status-chromecast-binding/80934/25?u=clemens_wunder

**Comment by smartnakh** [comment]
Thanks for this fix . What is it released ?

**Comment by vitalidze** [comment]
I have just released the 0.11.2 version with the fix. It will become available very soon.
