### ISSUE TITLE
Build failure on Travis

### ISSUE THREAD

**Issue by SubJunk** [vitalidze/chromecast-java-api-v2#124]
I'm not sure what the cause of this failure is, since the fault may be with Travis or jackson-core, but we recently started getting the failure despite making no changes, between the 7th and 22nd of Feb.
You can see here https://github.com/UniversalMediaServer/UniversalMediaServer/compare/master...OpenJDKTesting?expand=1 that the only thing that changed was a whitespace test, that's just there to illustrate that there really were no changes on my end.

Error from Travis:

```
Failed to execute goal on project ums: Could not resolve dependencies for project net.pms:ums:jar:9.2.1-SNAPSHOT: Failed to collect dependencies at su.litvak.chromecast:api-v2:jar:0.11.2 -> com.fasterxml.jackson.core:jackson-databind:jar:2.9.0,pr4-SNAPSHOT: Failed to read artifact descriptor for com.fasterxml.jackson.core:jackson-databind:jar:2.9.0,pr4-SNAPSHOT: Failure to find com.fasterxml.jackson:jackson-bom:pom:2.9.0.pr4-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
```

I can't reproduce the failure locally.

**Comment by vitalidze** [comment]
It appears that at some point a new snapshot version of the jackson was present in the repository. The version was broken or so and I think now it has been removed from there. My project is using the version range for jackson dependency. I would expect this to happen from time to time and I think the snapshot repository use needs to be avoided.

**Comment by SubJunk** [comment]
I guess a possible fix would be to be more specific with the jackson version, and periodically bump it, instead of doing the range. I understand that's not always desirable, but for projects where code is blocked from merging if CI fails, it is a big deal to have a failure like this

**Comment by SubJunk** [comment]
Proposed fix at https://github.com/vitalidze/chromecast-java-api-v2/pull/127

**Comment by wborn** [comment]
> I understand that's not always desirable, but for projects where code is blocked from merging if CI fails, it is a big deal to have a failure like this

You're not alone with this. All projects that have this dependency will run into this. We explicitly excluded jackson from it and added a fixed version. See https://github.com/openhab/openhab-addons/pull/7258.

**Comment by SubJunk** [comment]
@wborn that workaround fixed it for me in the meantime, thanks for your comment!

**Comment by vitalidze** [comment]
Thank you for bringing my attention and for the suggestion to fix. I will consider setting multiple explicit versions for 2.8, 2.9 and 2.10 instead of range. Hope this will help everyone. Will try to release the new version today.

**Comment by vitalidze** [comment]
I have just released a new version of the library (`0.11.3`) with the more strict dependencies on jackson. This should fix the issue. Please create a new ticket if it does not.

**Comment by SubJunk** [comment]
@vitalidze I have confirmed the fix at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1966/commits/7b130dfed79464a0e536a6e229b829896c1a8ea9
Thanks!

**Comment by vitalidze** [comment]
@SubJunk  awesome. I am happy to read that!
