### ISSUE TITLE
StreamType Enum are case sensitve

### ISSUE THREAD

**Issue by MrStevenFeldman** [vitalidze/chromecast-java-api-v2#15]
In the latest version, the Media.StreamType enum types are lowercase, however the specifications and some apps (pandora) use all caps.

https://developers.google.com/cast/docs/reference/receiver/cast.receiver.media#.StreamType

"W/s*.l*.c*.a*.v*.Channel: Error while reading: Can not construct instance of su.litvak.chromecast.api.v2.Media$StreamType from String value 'BUFFERED': value not one of declared Enum instance names"

Should they be changed to all caps or should additional logic be added to make case not a factor?

**Comment by vitalidze** [comment]
I don't know. Probably it should be case-insensitive, since in example provided by @haku it is in lower case while in specification and in pandora case it is upper-case. I have asked about that in #14 Let's wait for an answer.

**Comment by vitalidze** [comment]
I have just merged your pull request #16 and added upper-case enum elements for `StreamType` along with unit test. Let me know if it works for you with Pandora.
