### ISSUE TITLE
New fields for Application and Volume in firmware 1.19.62291

### ISSUE THREAD

**Issue by jonesman** [vitalidze/chromecast-java-api-v2#30]
Hi, one of my ChromeCasts was updated to this new firmware today, there is no mention of it on the ChromeCast forum yet, but here they say they'll post something soon: https://productforums.google.com/forum/#!topic/chromecast/VNYVaZHBNU8;context-place=topicsearchin/chromecast/changelog.
I couldn't get this ChromeCasts status anymore, after enabling the debug messages in the Channel class, i could see that the following fields had been added/changed:

Status:
Removed boolean isActiveInput
Removed boolean isStandby

Application:
New boolean isIdleScreen (seems true only if the Backdrop app is running)

Volume:
New String controlType ("attenuation" in my case)
New double stepInterval (0.05000000074505806)

Here are some JSON status responses:

**Backdrop, new FW:**
`{"requestId":1,"status":{"applications":[{"appId":"E8C28D3C","displayName":"Backdrop","isIdleScreen":true,"namespaces":[{"name":"urn:x-cast:com.google.cast.sse"}],"sessionId":"E5D50197-E550...","statusText":"","transportId":"web-5"}],"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}`

**Casting a tab from Chrome, new FW:**
`{"requestId":1,"status":{"applications":[{"appId":"0F5096E8","displayName":"Chrome Mirroring","isIdleScreen":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.webrtc"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.cast.debug"}],"sessionId":"73D2358A-793C...","statusText":"null (Tab)","transportId":"shell-v2mirroring-1"}],"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}`

**Backdrop, old FW (1.18.55065):**
`{"requestId":1,"status":{"applications":[{"appId":"E8C28D3C","displayName":"Backdrop","namespaces":[{"name":"urn:x-cast:com.google.cast.sse"}],"sessionId":"1CAFD4C1-39BD...","statusText":"","transportId":"web-3"}],"isActiveInput":true,"isStandBy":false,"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}`

After adding the fields everything went back to normal.
The only thing i'm doing is getStatus() and launchApp(), so i don't know if anything else has changed.
Thanks for making this library!

**Comment by vitalidze** [comment]
Hi

Thank you for reporting. Can you please kindly file a pull request so I will merge your changes to the upstream? Then I will release a new version with updated model.

**Comment by jonesman** [comment]
OK, the code i had just ignored the new values, i have updated it now to store them.
Couldn't run it yet (no device), hope to run it tomorrow (today) just to be sure.

**Comment by vitalidze** [comment]
Thank you. I have added couple of comments. I think all tests which check parsing of values in old format must be updated. If some are missing for new format then they must be added. Can you please kindly do that? Or I will do it when I find some free time.

**Comment by jonesman** [comment]
OK, i will look at the tests again and make sure they new fields are included.
I will put the change to startDiscovery in a different request, i knew i should have done so..
The code is tested to be working with both the older and current firmware and i will make a new pull request after fixing your comments.

**Comment by vitalidze** [comment]
Thank you. I appreciate that.

**Comment by jonesman** [comment]
I updated the audio test, but didn't touch the Pandora test because i thought wrong defaults might be confusing there (i don't know the values for either regular audio nor Pandora).
The discovery stuff is back to normal. I noticed i didn't have to make a new pull request (new to git),
so it's updated with the last commit, hope that does it :)

**Comment by jonesman** [comment]
Sorry about the spaces that were removed, i have learned not to use auto-format on other peoples files, they're fixed now.

**Comment by vitalidze** [comment]
Thank you. I have merged your changes, added tests per your messages, please see https://github.com/vitalidze/chromecast-java-api-v2/commit/e132f538668b1687270999c43fd35d4c6f142889 and https://github.com/vitalidze/chromecast-java-api-v2/commit/121c0fc42f96225c51542d8c25fe50a9f983cca8

**Comment by vitalidze** [comment]
Also I have released new version of the library, it is available [in maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22su.litvak.chromecast%22%20AND%20a%3A%22api-v2%22).

**Comment by jonesman** [comment]
Thanks for the update, glad you could make some proper tests from the JSON dumps!
