### ISSUE TITLE
ChromeCast.load not showing title

### ISSUE THREAD

**Issue by MCMastery** [vitalidze/chromecast-java-api-v2#37]
When I use `chromecast.load("Title", null, url, "audio/mpeg");`, the song is played, but the title "Title" cannot be seen (`url` is of course the URL of the audio file URL).

**Comment by haku** [comment]
This might be a useful hint:
https://github.com/haku/toadcast/blob/master/src/main/java/com/vaguehope/toadcast/PlayingState.java#L112
https://github.com/haku/toadcast/blob/master/src/main/java/com/vaguehope/toadcast/GoalSeeker.java#L273
(worked out from the Chromecast dev docs)

**Comment by MCMastery** [comment]
Thank you!
