### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by BBruch** [vitalidze/chromecast-java-api-v2#42]
Hi, 

I tried really hard to read a message from receiver-app like 
" window.messageBus.send(event.senderId, "This is the message");" 
or 
"var evt = "{\"responseType\":\"APPEVENT\",\"requestId\":0,\"event\":{\"msg\":\"This is the message\"}}";window.messageBus.send(event.senderId, evt);"

...but I cannot find out how this could work in sender-app!!

How can I achieve to read these messages in my sender.app ?

Always get an: WARNUNG: There was an OPT answer. Not currently handled. Option code: 65002 data: 4C9EAE79EDD01E68
Aug 10, 2016 3:17:15 PM javax.jmdns.impl.DNSIncoming readAnswer

Because I don't know how to handle this.

Thanks in advance. And I thank you for your work so far. I appreciate it.

Benjamin ( a beginner in JAVA)

**Comment by jruesga** [comment]
@BBruch, from the receiver you need to register the castMessageBus

`window.castMessageBus = window.castReceiverManager.getCastMessageBus('urn:x-cast:<namespace>');`


and then you can use it to send messages as:

`window.castMessageBus.send(to, JSON.stringify(msg));`


On the sender side, just register a ChromeCastSpontaneousEventListener and check events for your namespace.


Checkout https://github.com/jruesga/PhotoPhase/blob/master/site/receiver.js for the receiver and https://github.com/jruesga/PhotoPhase/blob/master/app/src/main/java/com/ruesga/android/wallpapers/photophase/cast/CastServer.java#L97 for the sender.

**Comment by vitalidze** [comment]
Any update on this issue?

**Comment by BBruch** [comment]
Haven't had the chance to check out the recommended solution. But think it will work out. 
@jruesga thx
@vitalidze you can close it
