### ISSUE TITLE
Mediastatus NPE with 0.9.3 version

### ISSUE THREAD

**Issue by Sami32** [vitalidze/chromecast-java-api-v2#51]
@vitalidze I assume that it will be more appropriate to post this issue there. [UMS #1030](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1030#issuecomment-256772308)
This user get issue with it Chromecast while using the firmware from 14 october 2016 (1.21.74816), few days after that Google announced his new  _Chromecast Ultra_ during the #MadeByGoogle event (maybe that could explain the `extendedStatus` add)

0.9.3 version added some NPE issues:
https://github.com/vitalidze/chromecast-java-api-v2/blob/master/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java#L194
`MediaStatus mediaStatus = channel.getMediaStatus(status.getRunningApp().transportId);`

On an other user log it was that NPE:
https://github.com/vitalidze/chromecast-java-api-v2/blob/master/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java#L185
`return channel.getMediaStatus(getRunningApp().transportId);`

**EDIT**: I will post the new log of the user when he will send it.
For now, i only have the log with the **0.9.2 version** with the "LOAD_FAILED" status.

> {"type":"MEDIA_STATUS","status[{"mediaSessionId":1,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"media":{"contentId":"C:\Users\Residentcl\Desktop\927071182.png","contentType":"image/png"},"currentItemId":1,"extendedStatus":{"playerState":"LOADING","media":{"contentId":"C:\Users\Residentcl\Desktop\927071182.png","contentType":"image/png"}},"repeatMode":"REPEAT_OFF"}],"requestId":0}
> ..
>  Bad chromecast load: su.litvak.chromecast.api.v2.ChromeCastException: Unable to load media

[debug.7z.txt](https://github.com/vitalidze/chromecast-java-api-v2/files/557119/debug.7z.txt)

With **0.9.3 version**: again failed loads but this time _mediaStatus_ NPE appeared as well.
[debug-2.txt](https://github.com/vitalidze/chromecast-java-api-v2/files/557288/debug-2.txt) (NPE 185)
[debug-1.txt](https://github.com/vitalidze/chromecast-java-api-v2/files/557303/debug-1.txt) (NPE 194)

**Comment by vitalidze** [comment]
Thank you for reporting. However, according to the `debug-2.txt` at the moment of calling for `MediaStatus` there are no running application anymore:

````
DEBUG 2016-10-27 20:31:37.102 [Thread-23]  <-- {"requestId":326,"status":{"applications":[{"appId":"CC1AD845","displayName":"Default Media Receiver","isIdleScreen":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"c0f91372-d242-4b6f-ba6f-eb1561127fad","statusText":"Ready To Cast","transportId":"web-55"}],"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}
DEBUG 2016-10-27 20:31:37.103 [Thread-69]  --> {"type":"GET_STATUS","requestId":327}
DEBUG 2016-10-27 20:31:37.193 [Thread-23]  <-- {"requestId":0,"status":{"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}
DEBUG 2016-10-27 20:31:37.194 [Thread-23]  <-- {"type":"CLOSE"}
DEBUG 2016-10-27 20:31:37.194 [Thread-23]  <-- {"requestId":327,"status":{"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}
INFO  2016-10-27 20:31:37.196 [Thread-69] Exception in thread "Thread-69" java.lang.NullPointerException
INFO  2016-10-27 20:31:37.197 [Thread-69] 	at su.litvak.chromecast.api.v2.ChromeCast.getMediaStatus(ChromeCast.java:185)
INFO  2016-10-27 20:31:37.197 [Thread-69] 	at net.pms.network.ChromecastPlayer$1.run(ChromecastPlayer.java:124)
INFO  2016-10-27 20:31:37.197 [Thread-69] 	at java.lang.Thread.run(Unknown Source)
````

It does not look like an issue in library. These methods like `getMediaStatus` or `play` from `debug-1.txt` are assuming you have already a running application. If you don't have it, then it will fail in any way. The only thing I can imagine to improve here is to throw some exception with user-friendly message like `There are no running application in ChromeCast`. What do you think?

From my point of view something needs to be changed in code written using the library. It should check whether there is still a running application and do something if there are no such.

Also this probably may be related somehow with #40, which is about `CLOSE` event received. In the log file I can see that event.

**Comment by Sami32** [comment]
@vitalidze I think it's a good idea, as not all the users using your Chromecast library have a Chromecast verbose debugging log and everyone is not Chromecast skilled as you ;-)

You make a good point, i totally missed that.
Hoping that these logs could help.

**Comment by Sami32** [comment]
@vitalidze Thanks.
