### ISSUE TITLE
Play slideshow

### ISSUE THREAD

**Issue by pamasa812** [vitalidze/chromecast-java-api-v2#53]
Hi together.
Which possibilities do I have to play a Slideshow on the Chromecast?
At the moment I run a thread which loads one media after the other.

Thank you!
Great evening.

**Comment by vitalidze** [comment]
I have no idea how to implement this. I guess you need a custom receiver application for the ChromeCast. I recommend to post similar question here: https://plus.google.com/communities/115742157569103585450

**Comment by mrothenbuecher** [comment]
@pamasa812 there are actually alot out there. [Chromecast-Kiosk](https://github.com/mrothenbuecher/Chromecast-Kiosk ) is an web application which uses a receiver application to cast websites. So you could use e.g. google slides.

**Comment by pamasa812** [comment]
Many thanks for your replies!
@mrothenbuecher I will try out Chromecast-Kiosk.
