### ISSUE TITLE
Protobuf file

### ISSUE THREAD

**Issue by fabianbergmark** [vitalidze/chromecast-java-api-v2#54]
I would like to translate this library so that it works on iOS. By looking at the code, I'm guessing that some of it is generated by protobuf. Do you have the .proto files available?

**Comment by vitalidze** [comment]
Here is the proto file: https://github.com/vitalidze/chromecast-java-api-v2/blob/master/src/main/resources/su/litvak/justdlna/chromecast/v2/cast_channel.proto

AFAIK it is also available somewhere in chromium repository.
