### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by leo81267** [vitalidze/chromecast-java-api-v2#56]
Hi , 

I'm trying to use this library and followed the steps mentioned in <MyProject>/app/build.gradle

1) In the latest Android Studio , there is "runtime" dependencies. So I modified it as 
dependencies {
// ...
    compile 'su.litvak.chromecast:api-v2:0.9.3'
// ...
}

and added the "api-v2-0.9.3.jar" to the Projects/libs/ folder.

When I try to run the app , it gives me the following error:

"
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: su/litvak/chromecast/api/v2/AppEvent.class
"

Has anyone faced this issue. Any suggestions ? Am I missing something ?

**Comment by vitalidze** [comment]
> and added the "api-v2-0.9.3.jar" to the Projects/libs/ folder.

Why do you add it there? It should be enough to put entry to `build.gradle` file. From my point of view you have included library into your project two times. That's why you are getting a `duplicate entry` error during some build step.

**Comment by leo81267** [comment]
Hi Vitalidze, 

Thanks  a lot . it worked.
