### ISSUE TITLE
Q: Chromecast server application

### ISSUE THREAD

**Issue by slux83** [vitalidze/chromecast-java-api-v2#57]
Hi,
I have a question about this API. Would it be possible to use it and implement a Chromecast server? So basically I'd like my app to act as Chromecast dongle and connect my mobile to it and stream the display (video+audio) into the java app.

Thanks

**Comment by vitalidze** [comment]
I don't think it can be used this way. The goal of this library is to act as "sender" for chromecast. But you can do some reverse engineering to implement your server so it will emulate chromecast behaviour.

**Comment by slux83** [comment]
Thank you for the quick answer
