### ISSUE TITLE
spontaneousEventReceived not called

### ISSUE THREAD

**Issue by lolodomo** [vitalidze/chromecast-java-api-v2#63]
A chromecast binding for openHAB was developed using this library.
I use it to cast to a Freebox Player mini, a box running Android TV.

When Youtube is casted to the box, I can control it with play and pause commands from openHAB. and this leads to calls to the method spontaneousEventReceived being called.

But when I control (play and pause) YouTube from my Android tablet and the YouTube application, that is outside openHAB, the method spontaneousEventReceived is not called in openHAB. In other words, openHAB is not notified about the updated media status.

Is it normal ?

PS: at the reverse, when I pause from openHAB, I can see that the state is updated in the YouTube application on my Android tablet.

**Comment by vitalidze** [comment]
This sounds like a bug. To verify it, it makes sense to enable debug logging to analyse all messages coming to/from ChromeCast device. Please enable debug logging and then post here the set of log messages.

**Comment by lolodomo** [comment]
Here are my logs:
```
22:34:32.234 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PONG"}
22:34:33.194 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PING"}
22:34:33.249 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PONG"}
22:34:54.278 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"requestId":0,"status":{"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
22:34:54.417 [DEBUG] [chromecast.handler.ChromecastHandler] - STATUS Media{volume: Volume{level: 1.0, muted: false, increment: 0.05, stepInterval: 0.05000000074505806, controlType: null}, applications: [], activeInput: false, standBy; false}
22:34:57.227 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"requestId":67,"status":{"applications":[{"appId":"233637DE","displayName":"YouTube","namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.youtube.mdx"},{"name":"urn:x-cast:com.google.cast.inject"}],"sessionId":"76B08AA7-7482-4DD4-9495-17FFB3467867","statusText":"YouTube","transportId":"mediashell-18"}],"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
22:34:57.233 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Unable to process request ID = 67, data: {"requestId":67,"status":{"applications":[{"appId":"233637DE","displayName":"YouTube","namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.youtube.mdx"},{"name":"urn:x-cast:com.google.cast.inject"}],"sessionId":"76B08AA7-7482-4DD4-9495-17FFB3467867","statusText":"YouTube","transportId":"mediashell-18"}],"volume":{"level":1.0,"muted":false}},"responseType":"RECEIVER_STATUS"}
22:34:57.715 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"requestId":0,"status":{"applications":[{"appId":"233637DE","displayName":"YouTube","namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.youtube.mdx"},{"name":"urn:x-cast:com.google.cast.inject"}],"sessionId":"76B08AA7-7482-4DD4-9495-17FFB3467867","statusText":"YouTube TV","transportId":"mediashell-18"}],"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
22:34:57.724 [DEBUG] [chromecast.handler.ChromecastHandler] - STATUS Media{volume: Volume{level: 1.0, muted: false, increment: 0.05, stepInterval: 0.05000000074505806, controlType: null}, applications: [Application{id: 233637DE, name: YouTube, sessionId: 76B08AA7-7482-4DD4-9495-17FFB3467867, statusText: YouTube TV, transportId: mediashell-18, isIdleScreen: false, namespaces: [Namespace{urn:x-cast:com.google.cast.cac}, Namespace{urn:x-cast:com.google.cast.media}, Namespace{urn:x-cast:com.google.youtube.mdx}, Namespace{urn:x-cast:com.google.cast.inject}]}], activeInput: false, standBy; false}
22:35:02.227 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:02.233 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:03.191 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PING"}
22:35:03.208 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PONG"}
22:35:08.233 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:08.236 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:14.244 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:14.248 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:20.246 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:20.248 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:26.252 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:26.255 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:32.256 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:32.259 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:33.191 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PING"}
22:35:33.201 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PONG"}
22:35:38.262 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"type":"PING"}
22:35:38.266 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  --> {"type":"PONG"}
22:35:43.053 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"requestId":0,"status":{"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
22:35:43.058 [DEBUG] [chromecast.handler.ChromecastHandler] - STATUS Media{volume: Volume{level: 1.0, muted: false, increment: 0.05, stepInterval: 0.05000000074505806, controlType: null}, applications: [], activeInput: false, standBy; false}
```
During this sequence, I play/pause several times from YouTube application.
Please note the warning at the beginning, maybe that is the source of the problem ?

**Comment by vitalidze** [comment]
This not a "Spontaneous" event because it has a non-zero `requestId`

````
22:34:57.227 [DEBUG] [su.litvak.chromecast.api.v2.Channel ] -  <-- {"requestId":67,"status":{"applications":[{"appId":"233637DE","displayName":"YouTube","namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.youtube.mdx"},{"name":"urn:x-cast:com.google.cast.inject"}],"sessionId":"76B08AA7-7482-4DD4-9495-17FFB3467867","statusText":"YouTube","transportId":"mediashell-18"}],"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
22:34:57.233 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Unable to process request ID = 67, data: {"requestId":67,"status":{"applications":[{"appId":"233637DE","displayName":"YouTube","namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.youtube.mdx"},{"name":"urn:x-cast:com.google.cast.inject"}],"sessionId":"76B08AA7-7482-4DD4-9495-17FFB3467867","statusText":"YouTube","transportId":"mediashell-18"}],"volume":{"level":1.0,"muted":false}},"responseType":"RECEIVER_STATUS"}
````

Spontaneous events are `STATUS` here, as you can see they have `requestId` equal to zero and looks like they are processed by some `chromecast.handler.ChromecastHandler`.

From the [documentation](https://developers.google.com/cast/docs/reference/messages):

> ## Media Status
>
> Sent after a state change or after a media status request. Only the MediaStatus objects that changed or were requested will be sent.
>
> | Name |	Type |	Description |
> | ------| -------- | ------ |
> | requestId |	integer |	ID used to correlate this status response with the request that originated it or 0 if the status message is spontaneous (not triggered by a sender request). Sender applications will generate unique request IDs by selecting a random number and continuously increasing it (they will not use 0). |
> | ... | ... | ... |

So, I don't see any issue here. Maybe I am missing something.

**Comment by lolodomo** [comment]
Ok, I try again. I should have created 2 different issues.

**First issue: warning "Unable to process request ID"**
This warning is produced when I start casting YouTube from my phone (not from openHAB) to Android TV. It may be a feedback broadcasted by Android TV in response to YouTube request to all connected applications ? Maybe in this case it is normal that openHAB can't handle this repsonse as it was not the application that requested the action ?

**The real issue: spontaneousEventReceived not called**
The last line you see in my logs is when from YouTube I stopped casting the video. In this case, spontaneousEventReceived  is called with a STAUS update event and it is what is expected.
BUT before stopping the cast, I pushed several times play and pause buttons in YouTube and as you can see in my logs I was never notified with a MEDIA_STATUS update.

**Comment by vitalidze** [comment]
> This warning is produced when I start casting YouTube from my phone (not from openHAB) to Android TV. It may be a feedback broadcasted by Android TV in response to YouTube request to all connected applications ? Maybe in this case it is normal that openHAB can't handle this repsonse as it was not the application that requested the action ?

I suppose this is the case. Currently responses are handled in two cases:

1) It was response to the request with expected identifier. Every request contains some generated non-zero identifier, which is then used to find response, process it and return result to request sender. If there is no matching processor for the response with received non-zero request id, then it is discarded with the above warning message.

2) It is a spontaneous event with zero identifier.

> The last line you see in my logs is when from YouTube I stopped casting the video. In this case, spontaneousEventReceived is called with a STAUS update event and it is what is expected.
> BUT before stopping the cast, I pushed several times play and pause buttons in YouTube and as you can see in my logs I was never notified with a MEDIA_STATUS update.

It is not called because ChromeCast does not send such data (as you can see in logs). I am not sure how to make ChromeCast sending that data, maybe there is a way to subscribe for all events somehow.

**Comment by lolodomo** [comment]
There is probably a way because at the reverse when I push the pause button in openHAB, I see an updated state in YouTube on my phone. So YouTube from my phone is notified by Android TV device of a changed media status triggered by openHAB.
Do you think it is working in this case because my phone initiated the cast ?

**Comment by vitalidze** [comment]
> Do you think it is working in this case only because my phone initiated the cast ?

It looks like that. But I am not sure. It requires reverse engineering, and probably it will be much better to do it from the web browser. I mean instead of phone use chrome extension to send youtube video.

**Comment by lolodomo** [comment]
Well, yes I could use a WEB browser.
Is it a kind of setup (with 3 devices) you could try to reproduce on your side ?

**Comment by lolodomo** [comment]
I took a quick look to chromecastplayer and I see that ir does not use ChromeCastSpontaneousEventListener. Instead it implements a thread that runs a getMediaStatus() every second. Maybe because ChromeCastSpontaneousEventListener is not fully reliable.

**Comment by vitalidze** [comment]
> Is it a kind of setup (with 3 devices) you could try to reproduce on your side ?

Sorry, I don't have much free time to reproduce this setup.

> I took a quick look to chromecastplayer and I see that ir does not use ChromeCastSpontaneousEventListener. Instead it implements a thread that runs a getMediaStatus() every second. Maybe because ChromeCastSpontaneousEventListener is not fully reliable.

From my point of view you should stick with same solution if it is official recipe from Google.

**Comment by lolodomo** [comment]
I just read the Google documentation (link you provided).
For a pause command: "Pauses playback of the current content. **Triggers a STATUS event notification to all sender applications."** So we should see a notification.

**Comment by vitalidze** [comment]
Ok, I have no idea why it does not send the notification. Maybe it's about the message, which gives the warning.

So, does it work for you if you do same from web browser extension? I mean if you change status from java-application, will it be reflected in the web browser?

**Comment by holmes** [comment]
In https://github.com/vitalidze/chromecast-java-api-v2/pull/73 I passed all STATUS events to the spontaneous event listener. I imagine it fixes this issue.

**Comment by vitalidze** [comment]
Closed due to inactivity.
