### ISSUE TITLE
getStatus returns null when in spontaneousEventReceived

### ISSUE THREAD

**Issue by lolodomo** [vitalidze/chromecast-java-api-v2#65]
When receiving an event, any call to Chromecast class methods leads to a NullPointerException because getStatus returns null. So getRunningApp() throws a NullPointerException and all other methods using getStatus or getRunningApp too.

My goal is to close the application when a notification I casted is finished. My only way to do it is I think to call stopApp() when I receive a particular event (IDLE state with no idle reason) and the app I launched is running. Due to this issue, I can't do it. Is there another way to achieve that ?

**Comment by vitalidze** [comment]
The only way to stop application that I know is to send a `Stop` request with appropriate `sessionId`. That session identifier can be taken from the application that was running. If you know that identifier (like stored it somewhere before application become 'IDLE'), then probably you can send a `Stop` request. The only way to do it currently is to create a custom `Stop` class for request and send a custom request. Maybe it will work without `sessionId`, but I haven't tried that. You can find documentation about custom requests in the [README.md file](https://github.com/vitalidze/chromecast-java-api-v2).

**Comment by lolodomo** [comment]
**The issue**
All Chromecast methiods produce a NPE when called from inside spontaneousEventReceived. In fact, this is due to getStatus method that returns null. Is it the expected behaviour ? Maybe by conception, in spontaneousEventReceived, we can only read the received event ?

**sopApp()**
stopApp() is working well when I use it. The only problem is that I can't call it when handling one received event (spontaneousEventReceived) due to the bug I just described.

**My use case**
From my application, I want to play (cast) a notification sound on my Android TV and then I want Android TV to return to its previous activity. No problem to start and play the notification. The only thing that I can't succeed is stopping the application at the end of the notification. My idea was to call stopApp when handling a particular event (spontaneousEventReceived) but due to the bug it is not possible. A workaround could be to create a new thread that will run stopApp(à when handling the event (spontaneousEventReceived). I will test that possible workaround.

**Comment by vitalidze** [comment]
> All Chromecast methiods produce a NPE when called from inside spontaneousEventReceived. In fact, this is due to getStatus method that returns null. Is it the expected behaviour ? Maybe by conception, in spontaneousEventReceived, we can only read the received event ?

I don't see any relation between `spontaneousEventReceived` and that NPE. The NPE means that ChromeCast device does not respond to the `getStatus` request for some reason. Can you please show full stack trace of the NPE? Also log records from `DEBUG` level might help.

**Comment by lolodomo** [comment]
I will provide the requested information later todayu but the stack will not help a lot.
For example, if I call getRunningApp(), the stack show a NPE here: https://github.com/vitalidze/chromecast-java-api-v2/blob/master/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java#L123
It is because the current code does not checks whether the result of getStatus is null.
The code should be updated to add a test and if the result of getStatus is null, getRunningApp() should return null.
But the real question is: why getStatus returns null ?

**Comment by vitalidze** [comment]
> I will provide the requested information later todayu but the stack will not help a lot.

Okay, thanks.

> For example, if I call getRunningApp(), the stack show a NPE here: https://github.com/vitalidze/chromecast-java-api-v2/blob/master/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java#L123
> It is because the current code does not checks whether the result of getStatus is null.
> The code should be updated to add a test and if the result of getStatus is null, getRunningApp() should return null.

There is no problem with updating the code. I think it should throw an exception though. The thing is that it will not help you anyhow: you will be getting NPE or Exception in other place.

> But the real question is: why getStatus returns null ?

I agree, I don't know why it returns null too. Thus, logging messages may help figuring that out.

**Comment by lolodomo** [comment]
Just for information, my workaround consisting to create a new thread to run the code is OK.

**Comment by vitalidze** [comment]
Thanks for the information. I am glad that you have some sort of solution.

**Comment by vitalidze** [comment]
Closed due to inactivity.
