### ISSUE TITLE
Error while reading: Unrecognized Windows Sockets error: 0: recv failed ?

### ISSUE THREAD

**Issue by Sami32** [vitalidze/chromecast-java-api-v2#66]
Datas coming from this log: https://drive.google.com/file/d/0B2kUHfEcnsF-dDVNMVl2dU9xNTA/view

> DEBUG 2017-01-22 19:42:03.845 [pool-5-thread-1] Found chromecast Chromecast-22c6d0b119a5939f5b16a9eef70b1dd5
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1]  --> {"type":"PING"}
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1]  --> {"type":"CONNECT","origin":{}}
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1] Reading MimeTypesChanges: "video/mpeg=video/mp4" (default: "")
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1] Reading MediaInfo: true (default: false)
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1] Reading RendererName: "Chromecast" (default: "Unknown renderer")
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1] Adding status button for Chromecast-22c6d0b119a5939f5b16a9eef70b1dd5
> DEBUG 2017-01-22 19:42:03.968 [pool-5-thread-1] Reading RendererIcon: "chromecast.png" (default: "unknown.png")
> DEBUG 2017-01-22 19:42:04.004 [Thread-87]  <-- {"type":"PONG"}
> DEBUG 2017-01-22 19:42:04.157 [sender-p1hntup0uo PING]  --> {"type":"PING"}
> DEBUG 2017-01-22 19:42:04.157 [sender-s2r5b05lns PING]  --> {"type":"PING"}
> WARN  2017-01-22 19:42:04.161 [Thread-77] Error while reading: Connection reset
> WARN  2017-01-22 19:42:04.161 [Thread-81] **Error while reading: Unrecognized Windows Sockets error: 0: recv failed**
> WARN  2017-01-22 19:42:04.161 [Thread-77]  <--  null payload in message 
> WARN  2017-01-22 19:42:04.161 [Thread-81]  <--  null payload in message 
> DEBUG 2017-01-22 19:42:04.972 [sender-c4jrw0qd2g PING]  --> {"type":"PING"}
> DEBUG 2017-01-22 19:42:05.013 [Thread-87]  <-- {"type":"PONG"}
> DEBUG 2017-01-22 19:42:05.343 [sender-sw11p0dl0k PING]  --> {"type":"PING"}
> WARN  2017-01-22 19:42:05.343 [Thread-41] Error while reading: Connection reset
> WARN  2017-01-22 19:42:05.343 [Thread-41]  <--  null payload in message 
> DEBUG 2017-01-22 19:42:06.731 [sender-h7zzxrqtr2 PING]  --> {"type":"PING"}

**DEBUG 2017-01-22 22:24:48.311 [sender-wpzpf6thwx PING]  --> {"type":"PING"}
WARN  2017-01-22 22:24:48.527 [Thread-145] Error while reading: Read timed out
WARN  2017-01-22 22:24:48.527 [Thread-145]  <--  null payload in message 
WARN  2017-01-22 22:24:49.367 [Thread-153] Error while reading: Read timed out
WARN  2017-01-22 22:24:49.367 [Thread-153]  <--  null payload in message 
DEBUG 2017-01-22 22:24:50.801 [sender-9y0rjetjl9 PING]  --> {"type":"PING"}
WARN  2017-01-22 22:24:50.801 [Thread-143] Error while reading: Read timed out
WARN  2017-01-22 22:24:50.801 [Thread-143]  <--  null payload in message** 

Not sure about the pertinence of this information, so feel free to close this issue if it's not useful..

**Comment by vitalidze** [comment]
I think this appears due to some networking issue. As you can see there are following messages as well:

> WARN 2017-01-22 19:42:04.161 [Thread-77] Error while reading: Connection reset

Brief googling leads me to [this thread on stackoverflow](http://stackoverflow.com/questions/135919/java-net-socketexception-software-caused-connection-abort-recv-failed), where people tell that TCP connection has been closed. From my point of view the best way to recover is to reconnect. However, currently there is no way to catch the situation when connection gets closed by some reason. To solve this I am thinking on merging the #27 #40 and #62 PRs somehow, so there will be both notification event (like `Closed` event from #27 #40) and a way to recover automatically (like `autoReconnect` flag discussed a bit in #62).

Anyway, thank you for reporting this.

**Comment by maggu2810** [comment]
@vitalidze I still have that close events and the reopen support in my setup running.
If you will work on such an integration I will be interested, too.

**Comment by vitalidze** [comment]
@maggu2810 FYI, I have just pushed changes, which are mostly taken from #62. Also I have taken some changes from your PR. I plan to release new version this week with all these changes. I think it will be a major release, like `0.10.0`

**Comment by vitalidze** [comment]
FYI I have released 0.10.0 today and it is already available in maven central.

**Comment by Sami32** [comment]
Great :+1: 

I'll push a PR and hopefully it'll be merged for the next version.
Thank you to all of you for your nice work.

**Comment by Sami32** [comment]
@vitalidze Do get some compilation issue as well ?
> [ERROR] /home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/network/ChromecastMgr.java:[46,33] no suitable constructor found for ChromeCast(javax.jmdns.JmDNS,java.lang.String) constructor su.litvak.chromecast.api.v2.ChromeCast.ChromeCast(java.lang.String,int) is not applicable (actual argument javax.jmdns.JmDNS cannot be converted to java.lang.String by method invocation conversion) constructor su.litvak.chromecast.api.v2.ChromeCast.ChromeCast(java.lang.String) is not applicable (actual and formal argument lists differ in length)

**Comment by vitalidze** [comment]
I don't have it. In #59 we have hidden the constructor with `JmDNS` argument because it is implementation-specific. I can see here https://github.com/UniversalMediaServer/UniversalMediaServer/blob/86502e6a72005cf18055f8eb118f85d2d833a004/src/main/java/net/pms/network/ChromecastMgr.java#L23 it is being used. It makes sense to change that class, so it uses the `ChromeCasts` class instead of `JmDNS`.

**Comment by Sami32** [comment]
@vitalidze Thank you for your help :-)

**Comment by Nadahar** [comment]
@vitalidze What a mess, I didn't see this answer until after I posted in #59. I usually don't want to touch code I can't debug, which is the case here as I have no Chromecast, could you elaborate on:
> It makes sense to change that class, so it uses the ChromeCasts class instead of JmDNS.

We obviously have to use another constuctor, but it seems our implementation is heavily dependent on JmDNS so I don't quite see how to change it without refactoring a lot - which I can't without a Chromecast.

**Comment by vitalidze** [comment]
Well, I can try filing a PR if you cannot handle it yourself. I have tried describing how to fix your class in #59 . For me it looks like a little change, say "refactoring".

**Comment by Sami32** [comment]
@vitalidze @maggu2810  Thank you for you help and work :smile: 
It's seem that it fixed the issue, though he get appearing/disappearing Chromacast renderer, i suspect that coud be it's network, as you suggested.

I saw some messages in the user's log without being able to understand if it's expected or not:
> WARN  2017-02-18 23:06:19.767 [Thread-23] Unable to process request ID = 19, data: {"requestId":19,"status":{"applications":[{"appId":"CC1AD845","displayName":"Default Media Receiver","isIdleScreen":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.broadcast"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"b6cce8b7-6ccb-4172-8346-c3742336043f","statusText":"Ready To Cast","transportId":"b6cce8b7-6ccb-4172-8346-c3742336043f"}],"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"responseType":"RECEIVER_STATUS"}

[debug.txt](https://github.com/vitalidze/chromecast-java-api-v2/files/787753/debug.txt)
