### ISSUE TITLE
Create a sample app?

### ISSUE THREAD

**Issue by holmes** [vitalidze/chromecast-java-api-v2#75]
I created a quick command line app to experiment with the API. Any interest in creating a separate module and checking it in?

It's super simple and pretty dumb, but it shows the functionality of the library and let's you see how a real ChromeCast interacts with the library.

**Comment by vitalidze** [comment]
Well, I don't think it is a good idea to create a separate module inside this repository. From my point of view it makes sense to create a separate repo with sample app.

To be honest I have such app myself, which is included in the codebase of library project, in 'unit' tests. It does some basic workflow with ChromeCast and I always run it before releasing new version of library to be sure that basic things work just fine.

**Comment by holmes** [comment]
Cool w/ me.
