### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by Gmentsik** [vitalidze/chromecast-java-api-v2#79]
How can you start a Netflix video?

I have tried to launch "Netflix" Application but had no success, Also I can't seem to find any list of application IDs.

Thank your for this API, it is really interesting and makes Alexa much much cooler!

**Comment by vitalidze** [comment]
> How can you start a Netflix video?

I don't know, it's better to look for some documentation on how to start it from android/iOS chromecast app. Then it should be fairly easy to do same using the library.

> I have tried to launch "Netflix" Application but had no success, Also I can't seem to find any list of application IDs.

I am not aware of such list as well.

> Thank your for this API, it is really interesting and makes Alexa much much cooler!

Can you please tell me how ChromeCast is related with Alexa? (Alexa is Amazon Echo or what do you mean?)

**Comment by vitalidze** [comment]
That sounds awesome.

I have spent some time googling on netflix running on ChromeCast. It looks like it will be quite complicated to run it because according to https://github.com/balloob/pychromecast/issues/53 netflix is using a proprietary API with encrypted set of commands.

**Comment by vitalidze** [comment]
Closed due to inactivity.
