### ISSUE TITLE
DashCast Question/Help/Possible Bug

### ISSUE THREAD

**Issue by kamenomagic** [vitalidze/chromecast-java-api-v2#83]
This is my current snippet:

`chromecast.send(dashcastNamespace, new ChromecastRequest(url, true, false, 0));`

And the chromecastRequest class is the exact same as the one on the Readme page.

I successfully start the chromecast app, and see my receiver on the screen, but when I execute that chromecast.send(...), it displays the receiver.html (doesn't change) with the error page of my spring boot tomcat server, even though the url is set to something like http://www.google.com. It's really weird to me cause I basically am just using code that is on the repo page. (To be clear of the behaviour I'm seeing, it displays the error page like 404 of the server that the receiver.html page is hosted on overlayed ontop of the receiver.html page whenever I call send. This happens even when the url I am sending to the dashcast receiver is a public url to on some other domain, like google.com. When I cast using the dashcast sender html page, it works correctly, but the send mehod to the same url with the same settings does not work.)

I also have looked through the smoke test in the repo, but it seems confusing because it uses both the Request and Response classes, and it seems pretty much exactly the same to what I'm doing.

I am simply trying to display a webpage, for example. I am able to cast to the dashcast app using the dashcast sender app, but not using the custom request class. 

Please let me know if you need more info, any help is much appreciated.

**Comment by vitalidze** [comment]
Here is the code I am using for testing next version of this library before releasing (integration test). It's using DashCast and works just fine for me:

````java
public class Main {
    public static void main(String[] args) throws Exception {
        ChromeCast chromecast = new ChromeCast("192.168.10.207");

        testDashCast(chromecast);

        chromecast.disconnect();

        Thread.sleep(10 * 1000);
    }

    static class DashCastRequest implements Request {
        @JsonProperty
        final String url;
        @JsonProperty
        final boolean force;
        @JsonProperty
        final boolean reload;
        @JsonProperty("reload_time")
        final int reloadTime;

        private Long requestId;

        public DashCastRequest(String url,
                               boolean force,
                               boolean reload,
                               int reloadTime) {
            this.url = url;
            this.force = force;
            this.reload = reload;
            this.reloadTime = reloadTime;
        }

        @Override
        public Long getRequestId() {
            return requestId;
        }

        @Override
        public void setRequestId(Long requestId) {
            this.requestId = requestId;
        }
    }

    static void testDashCast(ChromeCast chromecast) throws Exception {
        runApp(chromecast, "5C3F0A3C");

        chromecast.send("urn:x-cast:es.offd.dashcast",
                new DashCastRequest("http://yandex.ru", true, false, 0));
    }

    static void runApp(ChromeCast chromecast, String appId) throws Exception {
        // Get device status
        Status status = chromecast.getStatus();
        // Run application if it's not already running
        if (chromecast.isAppAvailable(appId)) {
            if (status.isAppRunning(appId)) {
                chromecast.stopApp();
            }
            chromecast.launchApp(appId);
        }
    }
}
````

I have made another test and it shows me the front page of yandex.

So, if you just copy and paste above code (replace with the IP address of your chrome cast device of course) and run it, will it show you the correct page?

**Comment by kamenomagic** [comment]
So it looks like very similar results between the two appIds. I have downloaded dashCast and made customizations, so it's slightly different, but when I run the above code it gives me a 404 on my server that is serving the receiver. 

I also tried with the app ID you have above (5C3F0A3C), and it gave me a 404 on github which is really weird. Here's the code I used:

`runApp(chromecast, "5C3F0A3C");
    chromecast.send("urn:x-cast:es.offd.dashcast", new ChromecastRequest("https://www.google.com", true, false, 0));`

And it successfully starts the chromecast app (for both my personal app ID and that one above), but then on the screen it shows a 404 on either my personal server, or when I use 5C3F0A3C it shows a 404 on github. 

I'm not sure what's making it behave differently from what you are seeing

**Comment by kamenomagic** [comment]
Just to make sure, I ran your code exactly (replacing only the IP of my chromecast) and got the same results:
It successfully starts the DashCast app, but instead of navigating to yandex.ru or google.com or whatever, it displays github's 404.

And what's weird is if I use the dash cast sender, it successfully displays the pages, but from the Java code it only shows 404 pages

**Comment by kamenomagic** [comment]
Maybe version of chromecast or something?

**Comment by quanticc** [comment]
I ran into this as well, and it's related to the jackson mapper version. The version used in this project is very old and used more lenient defaults. More recent versions of jackson don't let you serialize fields without getters (unless you tell it to make them visible), so DashCastRequest is only serializing requestId.

By modifying the class to have getters for all other properties (or making the fields public), it works as expected in jackson-databind 2.9.x.

**Comment by kamenomagic** [comment]
That worked just right! Thanks so much for taking time to respond, @quanticc, I've been trying to solve this for like months. I remember having issues with conflicting dependencies with jackson that I eventually solved but it's popped up as having issues again, so I'll have to keep my eye out for it in the future. 

@vitalidze I'm not sure if you want to go ahead and close the issue or change something in the code, but either way let me know if you need anything from me. I'm going to close it, feel free to reopen it if you do want to make changes. Thanks for your help.

Happy casting.

**Comment by vitalidze** [comment]
@quanticc thank you very much for sharing this.

@kamenomagic I am not sure what to do with this as well. I think maybe it makes sense to configure the jackson for always handling all public properties to make it working with new version updates.

**Comment by kamenomagic** [comment]
Sounds good to me, maybe we’d should add the getters to the example code?

**Comment by vitalidze** [comment]
Hi @kamenomagic and @quanticc . Do you have a simple case for reproducing this issue with inability to serialize fields without getters/setters? I was trying to reproduce this issues with jackson 2.9.4 (latest at the moment of writing) without any luck. Can you please assist me with writing of a test case?

**Comment by quanticc** [comment]
@vitalidze If you don't explicitly add JsonProperty annotation to fields, for example like this:

```java
    static class DashCastRequest {
        final String url;
        final boolean force;
        final boolean reload;
        @JsonProperty("reload_time")
        final int reloadTime;

        private Long requestId;

        public DashCastRequest(String url,
                               boolean force,
                               boolean reload,
                               int reloadTime) {
            this.url = url;
            this.force = force;
            this.reload = reload;
            this.reloadTime = reloadTime;
        }

        public Long getRequestId() {
            return requestId;
        }

        public void setRequestId(Long requestId) {
            this.requestId = requestId;
        }
    }
```
You can replicate the issue, as you'd get: `{"requestId":null,"reload_time":0}`

Adding one of these makes it work:
- Getters
- Public fields
- JsonProperty
- Modifying the ObjectMapper with `mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)`

Failing test case [here](https://github.com/quanticc/test-issue-83/blob/master/src/test/java/JacksonTest.java).

**Comment by vitalidze** [comment]
@quanticc thank you very much for providing this test case. Still I am a bit lost here. An example both from this thread and from project's readme contains the `@JsonProperty` annotation on fields. So I don't understand why it didn't work for @kamenomagic 

Thus, for now  I think I will leave mapper configuration untouched.

Again thank you for spending time on this. I appreciate your help!
