### ISSUE TITLE
New firmware 1.28.100555 adds field 'launchedFromCloud' to Application

### ISSUE THREAD

**Issue by jonesman** [vitalidze/chromecast-java-api-v2#84]
Hello,

my ChromeCasts got a firmware update to version 1.28.100555 today,
and i couldn't get the device status anymore, because a new field "launchedFromCloud" was added to the Application object.
I will create a pull request where i have added the field and a test for the new status response.
I don't know anything about newer features of the Cast stuff, so i don't where the field is coming from.

**Comment by vitalidze** [comment]
I have just released new version with changes from your PR. I believe it should become available in Maven Central today.

Thank you very much for helping fixing this bug.

**Comment by jonesman** [comment]
Glad i could help!
