### ISSUE TITLE
IOException on disconnect

### ISSUE THREAD

**Issue by kivinn77** [vitalidze/chromecast-java-api-v2#87]
Thanks for your project. It really helped me in my chromecast automation. 

One minor issue (or inconvenience) I bumped into - IOException, when I try to disconnect ChromeCast object. Brief debug got me to the point, that you close SSL Socket in the Channel.java, while corresponding InputStream is waiting for read() operation. Even though you set "stop" flag in the ReadThread class instance, the run method never gets to "while (!stop)" check due to IOException caused by socket.close().

This is really confusing and I would suggest adding the following code:
<pre>`if (stop) {
  LOG.debug("Got IOException while reading due to stream being closed (stop==true)");
  continue;
 }` </pre>inside of IOException handler of Channel.ReadThread.run method

**Comment by vitalidze** [comment]
Thanks for your interest in project. Can you submit a PR with above changes?

**Comment by kivinn77** [comment]
OK. I'll move it there. 

I noticed that the changes with stop flag were submitted as a response to the already closed issue #10. So I thought it makes sense to raise this topic here, as an issue.

**Comment by kivinn77** [comment]
I've created a PR, hence, closed here.
