### ISSUE TITLE
ByteBuffer.flip error on Java9

### ISSUE THREAD

**Issue by comtel2000** [vitalidze/chromecast-java-api-v2#90]
The `su.litvak.chromecast.api.v2.Util#toArray(int value)` throws a NoSuchMethodExcetion for ByteBuffer.flip() on Java9. So fare the only issue with Java9 and it's easy to fix..

```
Exception in thread "interpreter" java.lang.NoSuchMethodError: Method flip()Ljav
a/nio/ByteBuffer; does not exist in class java.nio.ByteBuffer.  
```
that works for me with all jdk's:
```
    static byte[] toArray(int value) {
    	   return new byte[] {
    	            (byte)(value >> 24),
    	            (byte)(value >> 16),
    	            (byte)(value >> 8),
    	            (byte)value};
    }
```

**Comment by vitalidze** [comment]
I have just fixed it. Thanks for noticing. I have removed `ByteBuffer` completely from the `Util` class. Fix will be included into next release, which hopefully will happen at the end of this week.
