### ISSUE TITLE
Error during build project with this lib

### ISSUE THREAD

**Issue by GrishinSergey** [vitalidze/chromecast-java-api-v2#91]
I've tried to use this library in my project, but when I try to build project, an error aquired:
`Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/sergey/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.8.0-beta0/f90ef27de5a997d30c169cb706835e32d724ca96/slf4j-api-1.8.0-beta0.jar`

`Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing module-info.class`

`Error:com.android.dx.cf.iface.ParseException: unsupported class file version 53.0`
`Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.`

`> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/sergey/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.8.0-beta0/f90ef27de5a997d30c169cb706835e32d724ca96/slf4j-api-1.8.0-beta0.jar`

To my project I include the lib like this:
 implementation 'su.litvak.chromecast:api-v2:0.10.2'

AndroidStudio 3.0
Gradle 4.1
Gradle android studio plugin: 3.0.0
What it can be?

**Comment by vitalidze** [comment]
This means that an slf4j dependency, which is being used in your project is from java 9 (version 53.0 of class file means that). AFAIK it is not supported in android project.

I think this dependency was added automatically to your project because the library (chromecast java API) has such dependency without version specification. To solve this you should include a compatible version of slf4j-api library in your project explicitly.

**Comment by GrishinSergey** [comment]
ok, i'll try your suggestions, thank you

**Comment by GrishinSergey** [comment]
`
implementation 'org.slf4j:slf4j-api:1.7.25'
implementation 'eu.lp0.slf4j:slf4j-android:1.7.25-0'
`
could you tell me, I'm trying to use this version of slf4j in android, but the project does not compile with the same error. Maybe you know what version to put?
thank you in advance

**Comment by vitalidze** [comment]
I don't know which version to put. Does your project compile if you just include `slf4j-api` and `slf4j-android` without including chromecast-api? And from my point of view you should be getting a different error, at least not for `slf4j-api-1.8.0-beta0.jar` (the version should be changed).

**Comment by GrishinSergey** [comment]
`implementation 'org.slf4j:slf4j-api:1.7.25'`
`implementation 'eu.lp0.slf4j:slf4j-android:1.7.25-0'`
Yes, app compiles, and I can run it on device with some simple code from this logger lib.
I've try to compile `chromecast-java-api-v2` like this:
`implementation ('su.litvak.chromecast:api-v2:0.10.2') {`
`    transitive false`
`}`
And it compiles and run. But it crashes because, 
java.lang.NoClassDefFoundError: su.litvak.chromecast.api.v2.ChromeCasts$MyServiceListener
   at su.litvak.chromecast.api.v2.ChromeCasts.<init>(ChromeCasts.java:32)
   at su.litvak.chromecast.api.v2.ChromeCasts.<clinit>(ChromeCasts.java:31)
   at com.sagrishin.chromecastapiv2.MainActivity.onCreate(MainActivity.kt:15)
   at android.app.Activity.performCreate(Activity.java:6127)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2630)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
   at android.app.ActivityThread.access$900(ActivityThread.java:187)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
   at android.os.Handler.dispatchMessage(Handler.java:111)
   at android.os.Looper.loop(Looper.java:194)
   at android.app.ActivityThread.main(ActivityThread.java:5877)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

In sources of `chromecast-java-api-v2` I saw, that it used `javax.jmdns.ServiceListener` from `JmDNS`. If I'm right, it's another library for discovering devices in network. Maybe `chromecast-java-api-v2` depends  from it? Or `slf4j-api` depends?

**Comment by GrishinSergey** [comment]
Ok, I've added `implementation 'javax.jmdns:jmdns:3.4.1'` dependence, and app compiles, and runs.
So, for correctly working, In my case, I need to add dependencies:
`implementation ('su.litvak.chromecast:api-v2:0.10.2') {`
`    transitive false`
`}`
`implementation 'org.slf4j:slf4j-api:1.7.25'`
`implementation 'eu.lp0.slf4j:slf4j-android:1.7.25-0'`
 `implementation 'javax.jmdns:jmdns:3.4.1'`
Then it compiles without errors

**Comment by vitalidze** [comment]
I think it's better to exclude just the slf4j-api dependency in 'chromecast-api' dependency declaration instead of specifying the `transitive: false`. In this case you will always have all necessary dependencies without the need of specifying them manually. Have you tried that?

**Comment by GrishinSergey** [comment]
No, I don't know, that such syntax is possible :) I'll try it

**Comment by vitalidze** [comment]
Closed due to inactivity.
