### ISSUE TITLE
NoClassDefFoundError & Unable to load media exception

### ISSUE THREAD

**Issue by MeMyselfMC** [vitalidze/chromecast-java-api-v2#95]
Calling the following method throws an error in my application:
```
		if(System.console() != null) {
			System.out.println("Starting.." + System.lineSeparator());
			
			Scanner userInput = new Scanner(System.in);
			
			System.out.println("Please enter the local network address of the Chromecast you wish to connect to.");
			try {
				chromecast = new ChromeCast(InetAddress.getByName(userInput.nextLine()).getHostAddress());
			} catch(UnknownHostException ex) {
				System.err.println("Invalid local network address provided. The program will now exit.");
				
				exit(1);
			}
```
The exception (JRE 8):
```
Starting..

Please enter the local network address of the Chromecast you wish to connect to.

Exception in thread "main" java.lang.NoClassDefFoundError: su/litvak/chromecast/
api/v2/ChromeCast
        at io.memyself.chrtest.Main.main(Main.java:114)
Caused by: java.lang.ClassNotFoundException: su.litvak.chromecast.api.v2.ChromeC
ast
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```

The most closely related issue I could find to my actual question was https://github.com/vitalidze/chromecast-java-api-v2/issues/11.

Is this an API for desktop Java applications or Android? How does one use it correctly? Many things are unclear due to lack of documentation.

**Comment by jonesman** [comment]
Hi, that just means it could not find the library classes, you have to include the library's .jar in your classpath when running, like "java -cp pathto/library.jar ..."

**Comment by MeMyselfMC** [comment]
Thanks. I found a more convenient way to work around this using the Maven assembly plugin to compile along with the dependencies (I was previously using Eclipse), but now I stumbled upon a completely different error that's irrelevant to this issue.

I'm getting the unable to load media exception when running the following code:
```
					if(chromecast.isConnected()) {
						if(chromecast.isAppAvailable("CC1AD845") && !chromecast.getStatus().isAppRunning("CC1AD845")) {
							chromecast.launchApp("CC1AD845");
						}
						
						chromecast.load(new Media("(URL)", "PHOTO"));
					}
```

I've also tried using this instead:
```
chromecast.load("(URL)");
```

..but it still throws the same exception.

I'm trying to load a JPEG (.jpeg) image with dimensions 1280x720 (720p) served by a local web server that is accessible by all devices on the network. The URL is correct. According to the Google Cast Developers Reference on media support and one or two comments on other issues like this it should work, but it does not.

**Comment by larryjkl** [comment]
This is currently working for me; maybe add a delay after launching the app and making sure that it is running before calling load?
      
```
      Application application = chromecast.launchApp( "CC1AD845" );
      try {
        Thread.sleep( 5000 );
      } catch ( InterruptedException ex ) {
        ;
      }
      Status status = chromecast.getStatus();
      
      if( status.getRunningApp().id.equalsIgnoreCase( "CC1AD845" )) {
        MediaStatus mediaStatus = chromecast.load( renderUrl );

```

**Comment by larryjkl** [comment]
Sounds good; I forget why I had that there, maybe I was seeing something different. I'll try and remove the wait and see how it goes. Great library by the way.

**Comment by MeMyselfMC** [comment]
I tried using a .jpg file instead of .jpeg and it works.
